export const EmojiMockData = {
  '+1': 'https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png?v8',
  '-1': 'https://github.githubassets.com/images/icons/emoji/unicode/1f44e.png?v8',
  100: 'https://github.githubassets.com/images/icons/emoji/unicode/1f4af.png?v8',
  1234: 'https://github.githubassets.com/images/icons/emoji/unicode/1f522.png?v8',
  '1st_place_medal': 'https://github.githubassets.com/images/icons/emoji/unicode/1f947.png?v8',
  '2nd_place_medal': 'https://github.githubassets.com/images/icons/emoji/unicode/1f948.png?v8',
  '3rd_place_medal': 'https://github.githubassets.com/images/icons/emoji/unicode/1f949.png?v8',
  '8ball': 'https://github.githubassets.com/images/icons/emoji/unicode/1f3b1.png?v8',
  a: 'https://github.githubassets.com/images/icons/emoji/unicode/1f170.png?v8',
  ab: 'https://github.githubassets.com/images/icons/emoji/unicode/1f18e.png?v8',
  abacus: 'https://github.githubassets.com/images/icons/emoji/unicode/1f9ee.png?v8',
  abc: 'https://github.githubassets.com/images/icons/emoji/unicode/1f524.png?v8',
  abcd: 'https://github.githubassets.com/images/icons/emoji/unicode/1f521.png?v8',
  accept: 'https://github.githubassets.com/images/icons/emoji/unicode/1f251.png?v8',
  adhesive_bandage: 'https://github.githubassets.com/images/icons/emoji/unicode/1fa79.png?v8',
  adult: 'https://github.githubassets.com/images/icons/emoji/unicode/1f9d1.png?v8',
  aerial_tramway: 'https://github.githubassets.com/images/icons/emoji/unicode/1f6a1.png?v8',
  afghanistan: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1eb.png?v8',
  airplane: 'https://github.githubassets.com/images/icons/emoji/unicode/2708.png?v8',
  aland_islands: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1fd.png?v8',
  alarm_clock: 'https://github.githubassets.com/images/icons/emoji/unicode/23f0.png?v8',
  albania: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1f1.png?v8',
  alembic: 'https://github.githubassets.com/images/icons/emoji/unicode/2697.png?v8',
  algeria: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e9-1f1ff.png?v8',
  alien: 'https://github.githubassets.com/images/icons/emoji/unicode/1f47d.png?v8',
  ambulance: 'https://github.githubassets.com/images/icons/emoji/unicode/1f691.png?v8',
  american_samoa: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1f8.png?v8',
  amphora: 'https://github.githubassets.com/images/icons/emoji/unicode/1f3fa.png?v8',
  anchor: 'https://github.githubassets.com/images/icons/emoji/unicode/2693.png?v8',
  andorra: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1e9.png?v8',
  angel: 'https://github.githubassets.com/images/icons/emoji/unicode/1f47c.png?v8',
  anger: 'https://github.githubassets.com/images/icons/emoji/unicode/1f4a2.png?v8',
  angola: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1f4.png?v8',
  angry: 'https://github.githubassets.com/images/icons/emoji/unicode/1f620.png?v8',
  anguilla: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1ee.png?v8',
  anguished: 'https://github.githubassets.com/images/icons/emoji/unicode/1f627.png?v8',
  ant: 'https://github.githubassets.com/images/icons/emoji/unicode/1f41c.png?v8',
  antarctica: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1f6.png?v8',
  antigua_barbuda: 'https://github.githubassets.com/images/icons/emoji/unicode/1f1e6-1f1ec.png?v8',
};

export const OrganizationsMockData = [
  {
    avatar_url: 'https://avatar.test.com',
    id: 1,
    login: 'test_login',
    url: 'https://test.api.com/test',
  },
  {
    avatar_url: 'https://avatar2.test.com',
    id: 2,
    login: 'test_login2',
    url: 'https://test2.api.com/test2',
  },
];
