name: Build app and Deploy to storage
env:
  OUTPUT_PATH: ${{ github.workspace }}/build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: |
        yarn install
        yarn test
        yarn build
    - name: Package app
      uses: actions/upload-artifact@v1
      with:
        name: reactApp
        path: ${{ env.OUTPUT_PATH }}

  deployApp:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: reactApp
          path: ${{ env.OUTPUT_PATH }}

      - name: "Blob storage upload"
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: build
          container_name: $web
          connection_string: ${{ secrets.BLOBSTORAGECONNECTIONSTRING }}
